# Generated by Django 2.0.10 on 2019-01-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='status',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='permissionsroles',
            name='status',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='roles',
            name='status',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='userroles',
            name='status',
            field=models.CharField(default='', max_length=2),
        ),
    ]
